"""Add clinical models

Revision ID: 3c4276eb9824
Revises: 
Create Date: 2026-04-12 12:56:00.137511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c4276eb9824'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('alert_uid'))

    op.drop_table('alerts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alert_uid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('patient_id_number', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('severity', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('recommendation', mysql.TEXT(), nullable=True),
    sa.Column('source', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('alert_type', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.Column('dismissed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('alerts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('alert_uid'), ['alert_uid'], unique=True)

    # ### end Alembic commands ###
